import { SquadBlueprintDefinition, SQUAD_BLUEPRINT_VERSION } from "@/lib/squads/blueprints";

export const DEFAULT_SQUAD_BLUEPRINTS: SquadBlueprintDefinition[] = [
    {
        id: "blueprint-app-forge-crew",
        version: SQUAD_BLUEPRINT_VERSION,
        name: "App Forge Crew",
        description: "End-to-end app delivery squad for planning, implementation, and validation.",
        category: "Engineering",
        tags: ["coding", "build", "testing", "shipping"],
        author: "CatGPT Defaults",
        squad: {
            name: "App Forge Crew",
            goal: "Design, build, and test a production-ready application aligned with the user goal.",
            context: "Maintain concise plans, build incrementally, and validate each major change.",
            members: ["architect", "builder", "qa", "pm"],
            maxIterations: 8,
            orchestrator: {
                name: "OR",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                style: "assistant",
                voiceId: "en-US-ChristopherNeural",
            },
            interaction: {
                mode: "master_log",
                showMasterLog: true,
                showAgentMessagesInChat: false,
                includeDirectorMessagesInChat: false,
                userTurnPolicy: "on_demand",
            },
        },
        agents: [
            {
                key: "architect",
                name: "Architect Cat",
                role: "Technical Architect",
                systemPrompt: "Break goals into deliverable milestones, define architecture decisions, and reduce ambiguity before coding starts.",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                tools: ["mcp_all", "web_search"],
            },
            {
                key: "builder",
                name: "Builder Cat",
                role: "Implementation Engineer",
                systemPrompt: "Implement features with clean, maintainable code and keep changes scoped to the assigned task.",
                provider: "groq",
                model: "llama-3.1-8b-instant",
                tools: ["mcp_all", "shell_execute"],
            },
            {
                key: "qa",
                name: "QA Cat",
                role: "Quality Engineer",
                systemPrompt: "Design practical test plans, run focused validation, and report concrete defects with reproduction steps.",
                provider: "groq",
                model: "llama-3.1-8b-instant",
                tools: ["mcp_all", "shell_execute"],
            },
            {
                key: "pm",
                name: "PM Cat",
                role: "Delivery Coordinator",
                systemPrompt: "Track priorities, manage scope, and keep the team aligned to user outcomes and acceptance criteria.",
                provider: "groq",
                model: "gemma2-9b-it",
                tools: ["mcp_all"],
            },
        ],
    },
    {
        id: "blueprint-web-launch-pod",
        version: SQUAD_BLUEPRINT_VERSION,
        name: "Web Launch Pod",
        description: "Website-focused squad covering UX, frontend, backend integration, and launch quality.",
        category: "Web Development",
        tags: ["frontend", "backend", "ux", "launch"],
        author: "CatGPT Defaults",
        squad: {
            name: "Web Launch Pod",
            goal: "Ship a performant, user-friendly web product with reliable core flows.",
            context: "Prioritize accessibility, responsiveness, and measurable business outcomes.",
            members: ["ux", "frontend", "backend", "release"],
            maxIterations: 8,
            orchestrator: {
                name: "OR",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                style: "assistant",
                voiceId: "en-US-ChristopherNeural",
            },
            interaction: {
                mode: "master_log",
                showMasterLog: true,
                showAgentMessagesInChat: false,
                includeDirectorMessagesInChat: false,
                userTurnPolicy: "on_demand",
            },
        },
        agents: [
            {
                key: "ux",
                name: "UX Cat",
                role: "Web UX Designer",
                systemPrompt: "Define clear user flows, information hierarchy, and interaction patterns for real product usage.",
                provider: "groq",
                model: "gemma2-9b-it",
                tools: ["web_search", "mcp_all"],
            },
            {
                key: "frontend",
                name: "Frontend Cat",
                role: "Frontend Engineer",
                systemPrompt: "Build intentional, responsive UI and preserve consistency with the existing visual system.",
                provider: "groq",
                model: "llama-3.1-8b-instant",
                tools: ["mcp_all", "shell_execute"],
            },
            {
                key: "backend",
                name: "Backend Cat",
                role: "Backend Engineer",
                systemPrompt: "Design robust API and data layers, and keep implementation predictable and testable.",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                tools: ["mcp_all", "shell_execute"],
            },
            {
                key: "release",
                name: "Release Cat",
                role: "QA and Performance Engineer",
                systemPrompt: "Audit release quality, catch regressions, and verify speed and reliability before launch.",
                provider: "groq",
                model: "llama-3.1-8b-instant",
                tools: ["mcp_all", "shell_execute"],
            },
        ],
    },
    {
        id: "blueprint-product-design-studio",
        version: SQUAD_BLUEPRINT_VERSION,
        name: "Product Design Studio",
        description: "Research-to-spec product design squad for discovery, UX, and delivery-ready artifacts.",
        category: "Product Design",
        tags: ["research", "ux", "product", "specs"],
        author: "CatGPT Defaults",
        squad: {
            name: "Product Design Studio",
            goal: "Turn a product idea into validated flows, UX rationale, and actionable implementation specs.",
            context: "Balance user needs, business outcomes, and engineering feasibility.",
            members: ["research", "product", "content", "systems"],
            maxIterations: 7,
            orchestrator: {
                name: "OR",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                style: "assistant",
                voiceId: "en-US-ChristopherNeural",
            },
            interaction: {
                mode: "master_log",
                showMasterLog: true,
                showAgentMessagesInChat: false,
                includeDirectorMessagesInChat: false,
                userTurnPolicy: "on_demand",
            },
        },
        agents: [
            {
                key: "research",
                name: "Research Cat",
                role: "User Researcher",
                systemPrompt: "Gather concise market and user evidence, then summarize practical implications for product decisions.",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                tools: ["web_search", "mcp_all"],
            },
            {
                key: "product",
                name: "Product Designer Cat",
                role: "Product Designer",
                systemPrompt: "Define user journeys, wireflow logic, and UX rationale that engineering can implement confidently.",
                provider: "groq",
                model: "gemma2-9b-it",
                tools: ["mcp_all"],
            },
            {
                key: "content",
                name: "Content Cat",
                role: "UX Writer",
                systemPrompt: "Write clear product copy, labels, and instructional language that reduces confusion.",
                provider: "groq",
                model: "llama-3.1-8b-instant",
                tools: ["mcp_all"],
            },
            {
                key: "systems",
                name: "Systems Cat",
                role: "Design Systems Specialist",
                systemPrompt: "Translate product decisions into reusable UI patterns, tokens, and component-level guidance.",
                provider: "groq",
                model: "llama-3.1-8b-instant",
                tools: ["mcp_all"],
            },
        ],
    },
    {
        id: "blueprint-market-intel-cell",
        version: SQUAD_BLUEPRINT_VERSION,
        name: "Market Intel Cell",
        description: "Fast strategic research squad for market mapping, competitor analysis, and GTM recommendations.",
        category: "Market Research",
        tags: ["market", "competition", "strategy", "gtm"],
        author: "CatGPT Defaults",
        squad: {
            name: "Market Intel Cell",
            goal: "Produce a concise market brief, competitor matrix, and actionable go-to-market strategy.",
            context: "Use source-backed facts, call out assumptions, and separate signal from noise.",
            members: ["market", "competitive", "analyst", "strategy"],
            maxIterations: 6,
            orchestrator: {
                name: "OR",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                style: "assistant",
                voiceId: "en-US-ChristopherNeural",
            },
            interaction: {
                mode: "master_log",
                showMasterLog: true,
                showAgentMessagesInChat: false,
                includeDirectorMessagesInChat: false,
                userTurnPolicy: "on_demand",
            },
        },
        agents: [
            {
                key: "market",
                name: "Market Scout Cat",
                role: "Market Research Lead",
                systemPrompt: "Map customer segments, trends, and market dynamics with clear source-backed conclusions.",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                tools: ["web_search", "mcp_all"],
            },
            {
                key: "competitive",
                name: "Competitive Cat",
                role: "Competitive Intelligence Analyst",
                systemPrompt: "Compare top competitors by positioning, feature set, pricing, and strategic differentiation.",
                provider: "groq",
                model: "llama-3.1-8b-instant",
                tools: ["web_search", "mcp_all"],
            },
            {
                key: "analyst",
                name: "Insight Cat",
                role: "Data Synthesis Analyst",
                systemPrompt: "Condense findings into executive-ready insights, decision risks, and prioritized opportunities.",
                provider: "groq",
                model: "gemma2-9b-it",
                tools: ["mcp_all"],
            },
            {
                key: "strategy",
                name: "GTM Cat",
                role: "Go-To-Market Strategist",
                systemPrompt: "Convert research insights into practical positioning, channel, and launch recommendations.",
                provider: "groq",
                model: "llama-3.3-70b-versatile",
                tools: ["mcp_all"],
            },
        ],
    },
];

